apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  labels:
    app: python-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
      - image: python-service:flask-app:latest
        imagePullPolicy: Always
        name: python-service
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: flask-app_URL
          value: "http://ecsdemo-crystal.default.svc.cluster.local/crystal"
    
