
FROM amazonlinux


RUN yum update -y
RUN yum install -y python3 python3-dev python3-pip 

# copy the code 
COPY ./ ./app
WORKDIR ./app
#RUN python flask-api.py
RUN ls
RUN pip3 install -r requirements.txt

# health check
HEALTHCHECK --interval=10s --timeout=3s \
  CMD curl -f -s http://localhost:5000/todo/api/v1.0/tasks || exit 1
EXPOSE 5000
#ENTRYPOINT echo "Hello!"
ENTRYPOINT ["python3","flask-api.py"]
